[project]
name = "semordnilap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.8.5",
    "duckdb>=1.5.2",
    "stanza>=1.15.0",
    "tqdm>=4.67.1",
]

[project.scripts]
sp_corpus = "semordnilap.corpus.cli:main"
sp_corpus_wikisource = "semordnilap.corpus.wikisource:main"
sp_tag = "semordnilap.tagging.cli:main"
sp_ngrams = "semordnilap.ngrams.cli.extract:main"
sp_search_ngrams = "semordnilap.search.cli.find_ngrams:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "isort>=7.0.0",
    "jupyter>=1.1.1",
    "mypy>=1.19.1",
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]

[tool.ruff]
line-length = 79
target-version = "py313"
